### PR TITLE
Make jquery an optional dependency

### PR DESCRIPTION
**Pull request by zfarrell**
I pulled in changes from the upstream outlayer which make jquery optional.

### CODE REVIEW

**Comment by eiriklv** [comment]
Hey! Sorry I didn't see this PR until now :-) Sounds like a good idea to get rid of it since it isn't used (in my cases at least)

**Comment by chpio** [comment]
could you merge this PR?

**Comment by chpio** [comment]
Thank you. with this change my (unminified) js file moved from 1.1MB to 860KB

**Comment by eiriklv** [comment]
@t128 @zfarrell - is your reason for using this fork that the original does not load properly using webpack?

**Comment by chpio** [comment]
no, im using your _react-masonry-mixin_. The mixin depends on _masonry_, which depends on _outlayer_.

**Comment by eiriklv** [comment]
@t128 ah, figures :)

**Pull request merged**
